{% set version = "2.8.6" %}
{% set linux_version = "3.1.3" %}
{% set windows_base_url = "https://ffmpeg.zeranoe.com/builds/" %}

package:
  name: ffmpeg
  version: {{ version }}        # [not linux]
  version: {{ linux_version }}  # [linux]

source:
  fn: ffmpeg-{{ version }}-win32-static.7z                                       # [win32]
  url: {{ windows_base_url }}/win32/static/ffmpeg-{{ version }}-win32-static.7z  # [win32]
  sha256: 7af6acfd20094d29bfc4f2c07979d7d853e8e521869e52c344ba247a50485b8b       # [win32]
  fn: ffmpeg-{{ version }}-win64-static.7z                                       # [win64]
  url: {{ windows_base_url }}/win64/static/ffmpeg-{{ version }}-win64-static.7z  # [win64]
  sha256: 3e68fc7158cd6d8696ef1a5b0a6ad981409c42e11699245eb0e808a5922c0577       # [win64]
  fn: SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_02.02.2016.zip                                      # [osx]
  url: http://www.ffmpegmac.net/resources/SnowLeopard_Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_02.02.2016.zip  # [osx]
  sha256: 723f23b5c6c9451a1732fcd8978d6675d69d33162d8780aa1db7c18b3eb54edc                                             # [osx]
  # This Linux build is actually 3.1.3 but the downloads aren't versioned
  # so I'm relying on the MD5 provided on the website to protect accidental upgrades.
  fn: ffmpeg-release-64bit-static.tar.xz                                            # [linux64]
  url: http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz  # [linux64]
  md5: ea0d2e6b974559b529d048c498e371e5                                             # [linux64]

requirements:
  build:
    - 7zip  # [win]

test:
  commands:
    - ffmpeg -version
    - ffprobe -version

about:
  home: https://www.ffmpeg.org/
  license: LGPL
